spring:
  appllication:
    name: ${project.rootProject.name}
  profiles:
    active: dev
  application:
    name: amazon-review-collector
  sleuth:
    enabled: true
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411/
    enabled: true
    sender:
      type: web
    service:
      name: amazon-crawler-service
  cloud:
    function:
      definition: collectReviews;
    stream:
      kafka:
        binder:
          replication-factor: 1
#    stream:
#      bindings:
#        collectReviews-in-0:
#          destination: reviewInput
#        collectReviews-out-0:
#          destination: reviewOutput
#          group: demo
#        getReviews-in-0:
#          destination: processReview
#          group: demo


logging:
  level:
    org:
      springframework:
        cloud: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
    org.spring.kafka.config: DEBUG
##Spring actuator
management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include: ['configprops', 'env', 'health', 'info', 'jhimetrics', 'logfile', 'loggers', 'prometheus', 'threaddump']
  endpoint:
    health:
      show-details: when_authorized
      roles: 'ROLE_ADMIN'
      probes:
        enabled: true
    jhimetrics:
      enabled: true
  info:
    git:
      mode: full
  health:
    group:
      liveness:
        include: livenessState
      readiness:
        include: readinessState
    mail:
      enabled: false # When using the MailService, configure an SMTP server and set this to true
  metrics:
    export:
      # Prometheus is the default metrics backend
      prometheus:
        enabled: true
        step: 60
    enable:
      http: true
      jvm: true
      logback: true
      process: true
      system: true
    distribution:
      percentiles-histogram:
        all: true
      percentiles:
        all: 0, 0.5, 0.75, 0.95, 0.99, 1.0
    tags:
      application: ${spring.application.name}
    web:
      server:
        request:
          autotime:
            enabled: true

sentry:
  dsn: https://72af93dcb3774b118fa58bfa923ce7e9@o1082414.ingest.sentry.io/6090963
  trace-sample-rate: 1.0
  send-default-pii: true

