version: "3.8"
services:
  rabbitmq:
   image: "rabbitmq:3.8-management"
   container_name: "polar-rabbitmq"
   ports:
    - 5672:5672
    - 15672:15672
   environment:
    - RABBITMQ_DEFAULT_USER=user
    - RABBITMQ_DEFAULT_PASS=password