name: CD Pipeline

on:
  push:
    branches: [ master ]

jobs:

  build-service:
    name: Build Amazon Review Collector Microservice
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
      - name: Compile and test application
        run: |
          cd amazon-review-collector
          chmod +x gradlew
          ./gradlew build    
