name: CD Pipeline

on:
  push:
    branches: [ master ]
    
  workflow_dispatch:  
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'manually run workflow tags'
jobs:

  build-service:
    name: Build Amazon Review Collector Microservice
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Log level: ${{ github.event.inputs.logLevel }}"
          echo "Tags: ${{ github.event.inputs.tags }}"
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
      - name: Compile and test application
        run: |
          chmod +x gradlew
          ./gradlew build  
      - name: "Containerize and push image secret: ${{secrets.DOCKER_HUB_USER_NAME}} env:  ${{env.DOCKER_HUB_USER_NAME}}"
        run: |
           DOCKER_HUB_USER_NAME=${{secrets.DOCKER_HUB_USER_NAME}} DOCKER_HUB_PASSWORD=${{secrets.DOCKER_HUB_PASSWORD}} ./gradlew bootBuildImage
